//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigFileSpec) DeepCopyInto(out *ConfigFileSpec) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigFileSpec.
func (in *ConfigFileSpec) DeepCopy() *ConfigFileSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigFileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DigestSpec) DeepCopyInto(out *DigestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DigestSpec.
func (in *DigestSpec) DeepCopy() *DigestSpec {
	if in == nil {
		return nil
	}
	out := new(DigestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtraPort) DeepCopyInto(out *ExtraPort) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtraPort.
func (in *ExtraPort) DeepCopy() *ExtraPort {
	if in == nil {
		return nil
	}
	out := new(ExtraPort)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricFlavour) DeepCopyInto(out *FabricFlavour) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricFlavour.
func (in *FabricFlavour) DeepCopy() *FabricFlavour {
	if in == nil {
		return nil
	}
	out := new(FabricFlavour)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlavourSpec) DeepCopyInto(out *FlavourSpec) {
	*out = *in
	if in.Vanilla != nil {
		in, out := &in.Vanilla, &out.Vanilla
		*out = new(VanillaFlavour)
		**out = **in
	}
	if in.Fabric != nil {
		in, out := &in.Fabric, &out.Fabric
		*out = new(FabricFlavour)
		**out = **in
	}
	if in.Paper != nil {
		in, out := &in.Paper, &out.Paper
		*out = new(PaperFlavour)
		(*in).DeepCopyInto(*out)
	}
	if in.Forge != nil {
		in, out := &in.Forge, &out.Forge
		*out = new(ForgeFlavour)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlavourSpec.
func (in *FlavourSpec) DeepCopy() *FlavourSpec {
	if in == nil {
		return nil
	}
	out := new(FlavourSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForgeFlavour) DeepCopyInto(out *ForgeFlavour) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForgeFlavour.
func (in *ForgeFlavour) DeepCopy() *ForgeFlavour {
	if in == nil {
		return nil
	}
	out := new(ForgeFlavour)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GameServiceSpec) DeepCopyInto(out *GameServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GameServiceSpec.
func (in *GameServiceSpec) DeepCopy() *GameServiceSpec {
	if in == nil {
		return nil
	}
	out := new(GameServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JVMSpec) DeepCopyInto(out *JVMSpec) {
	*out = *in
	if in.ExtraArgs != nil {
		in, out := &in.ExtraArgs, &out.ExtraArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JVMSpec.
func (in *JVMSpec) DeepCopy() *JVMSpec {
	if in == nil {
		return nil
	}
	out := new(JVMSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JavaSpec) DeepCopyInto(out *JavaSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JavaSpec.
func (in *JavaSpec) DeepCopy() *JavaSpec {
	if in == nil {
		return nil
	}
	out := new(JavaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSpec) DeepCopyInto(out *MetricsSpec) {
	*out = *in
	if in.StatsExporter != nil {
		in, out := &in.StatsExporter, &out.StatsExporter
		*out = new(bool)
		**out = **in
	}
	if in.ModEndpoint != nil {
		in, out := &in.ModEndpoint, &out.ModEndpoint
		*out = new(EndpointSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSpec.
func (in *MetricsSpec) DeepCopy() *MetricsSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftInstance) DeepCopyInto(out *MinecraftInstance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftInstance.
func (in *MinecraftInstance) DeepCopy() *MinecraftInstance {
	if in == nil {
		return nil
	}
	out := new(MinecraftInstance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinecraftInstance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftInstanceList) DeepCopyInto(out *MinecraftInstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinecraftInstance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftInstanceList.
func (in *MinecraftInstanceList) DeepCopy() *MinecraftInstanceList {
	if in == nil {
		return nil
	}
	out := new(MinecraftInstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinecraftInstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftInstanceSpec) DeepCopyInto(out *MinecraftInstanceSpec) {
	*out = *in
	in.Flavour.DeepCopyInto(&out.Flavour)
	out.Java = in.Java
	in.JVM.DeepCopyInto(&out.JVM)
	if in.Mods != nil {
		in, out := &in.Mods, &out.Mods
		*out = make([]ModSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigFiles != nil {
		in, out := &in.ConfigFiles, &out.ConfigFiles
		*out = make([]ConfigFileSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Storage.DeepCopyInto(&out.Storage)
	in.Service.DeepCopyInto(&out.Service)
	if in.Autostart != nil {
		in, out := &in.Autostart, &out.Autostart
		*out = new(bool)
		**out = **in
	}
	in.Upgrade.DeepCopyInto(&out.Upgrade)
	in.Metrics.DeepCopyInto(&out.Metrics)
	out.Supervisor = in.Supervisor
	in.Resources.DeepCopyInto(&out.Resources)
	if in.PodOverrides != nil {
		in, out := &in.PodOverrides, &out.PodOverrides
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftInstanceSpec.
func (in *MinecraftInstanceSpec) DeepCopy() *MinecraftInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(MinecraftInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftInstanceStatus) DeepCopyInto(out *MinecraftInstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Resolved != nil {
		in, out := &in.Resolved, &out.Resolved
		*out = new(ResolvedStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Players != nil {
		in, out := &in.Players, &out.Players
		*out = new(PlayersStatus)
		**out = **in
	}
	if in.LastSave != nil {
		in, out := &in.LastSave, &out.LastSave
		*out = (*in).DeepCopy()
	}
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(UpgradeStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftInstanceStatus.
func (in *MinecraftInstanceStatus) DeepCopy() *MinecraftInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(MinecraftInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModSpec) DeepCopyInto(out *ModSpec) {
	*out = *in
	if in.Modrinth != nil {
		in, out := &in.Modrinth, &out.Modrinth
		*out = new(ModrinthSource)
		**out = **in
	}
	if in.Digest != nil {
		in, out := &in.Digest, &out.Digest
		*out = new(DigestSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModSpec.
func (in *ModSpec) DeepCopy() *ModSpec {
	if in == nil {
		return nil
	}
	out := new(ModSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModrinthSource) DeepCopyInto(out *ModrinthSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModrinthSource.
func (in *ModrinthSource) DeepCopy() *ModrinthSource {
	if in == nil {
		return nil
	}
	out := new(ModrinthSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaperFlavour) DeepCopyInto(out *PaperFlavour) {
	*out = *in
	if in.Build != nil {
		in, out := &in.Build, &out.Build
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaperFlavour.
func (in *PaperFlavour) DeepCopy() *PaperFlavour {
	if in == nil {
		return nil
	}
	out := new(PaperFlavour)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlayersStatus) DeepCopyInto(out *PlayersStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlayersStatus.
func (in *PlayersStatus) DeepCopy() *PlayersStatus {
	if in == nil {
		return nil
	}
	out := new(PlayersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedFile) DeepCopyInto(out *ResolvedFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedFile.
func (in *ResolvedFile) DeepCopy() *ResolvedFile {
	if in == nil {
		return nil
	}
	out := new(ResolvedFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedMod) DeepCopyInto(out *ResolvedMod) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedMod.
func (in *ResolvedMod) DeepCopy() *ResolvedMod {
	if in == nil {
		return nil
	}
	out := new(ResolvedMod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedStatus) DeepCopyInto(out *ResolvedStatus) {
	*out = *in
	if in.PaperBuild != nil {
		in, out := &in.PaperBuild, &out.PaperBuild
		*out = new(int64)
		**out = **in
	}
	if in.ServerJar != nil {
		in, out := &in.ServerJar, &out.ServerJar
		*out = new(ResolvedFile)
		**out = **in
	}
	if in.Mods != nil {
		in, out := &in.Mods, &out.Mods
		*out = make([]ResolvedMod, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedStatus.
func (in *ResolvedStatus) DeepCopy() *ResolvedStatus {
	if in == nil {
		return nil
	}
	out := new(ResolvedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSpec) DeepCopyInto(out *ServiceSpec) {
	*out = *in
	in.Game.DeepCopyInto(&out.Game)
	if in.ExtraPorts != nil {
		in, out := &in.ExtraPorts, &out.ExtraPorts
		*out = make([]ExtraPort, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSpec.
func (in *ServiceSpec) DeepCopy() *ServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageSpec) DeepCopyInto(out *StorageSpec) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.RetainOnDelete != nil {
		in, out := &in.RetainOnDelete, &out.RetainOnDelete
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageSpec.
func (in *StorageSpec) DeepCopy() *StorageSpec {
	if in == nil {
		return nil
	}
	out := new(StorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupervisorSpec) DeepCopyInto(out *SupervisorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupervisorSpec.
func (in *SupervisorSpec) DeepCopy() *SupervisorSpec {
	if in == nil {
		return nil
	}
	out := new(SupervisorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeSpec) DeepCopyInto(out *UpgradeSpec) {
	*out = *in
	if in.BackupBeforeUpgrade != nil {
		in, out := &in.BackupBeforeUpgrade, &out.BackupBeforeUpgrade
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeSpec.
func (in *UpgradeSpec) DeepCopy() *UpgradeSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeStatus) DeepCopyInto(out *UpgradeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeStatus.
func (in *UpgradeStatus) DeepCopy() *UpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(UpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VanillaFlavour) DeepCopyInto(out *VanillaFlavour) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VanillaFlavour.
func (in *VanillaFlavour) DeepCopy() *VanillaFlavour {
	if in == nil {
		return nil
	}
	out := new(VanillaFlavour)
	in.DeepCopyInto(out)
	return out
}
